# Generated by Django 3.2.8 on 2022-01-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_auto_20220116_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
