# Generated by Django 3.2.8 on 2022-03-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
        ('app4', '0002_remove_fooddonation_foodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='FoodRequest',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app6.foodrequest'),
            preserve_default=False,
        ),
    ]
