# Generated by Django 3.2.8 on 2022-03-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
        ('app4', '0003_fooddonation_foodrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothingDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothingType', models.CharField(max_length=200)),
                ('clothingQuantity', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.SlugField(max_length=500)),
                ('buildingNumber', models.CharField(max_length=1000)),
                ('tradeMark', models.SlugField(max_length=500)),
                ('clothingRequest', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app6.clothingrequest')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app4.usersignup')),
            ],
        ),
    ]
