# Generated by Django 3.2.8 on 2022-01-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_auto_20220117_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='confpassword',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
