# Generated by Django 3.2.8 on 2022-03-03 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
        ('app4', '0004_clothingdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyMaterialDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyMaterialType', models.CharField(max_length=200)),
                ('studyMaterialQuantity', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.SlugField(max_length=500)),
                ('buildingNumber', models.CharField(max_length=1000)),
                ('tradeMark', models.SlugField(max_length=500)),
                ('studyMaterialRequest', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app6.studymaterialrequest')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app4.usersignup')),
            ],
        ),
        migrations.CreateModel(
            name='otherDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherType', models.CharField(max_length=200)),
                ('otherQuantity', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.SlugField(max_length=500)),
                ('buildingNumber', models.CharField(max_length=1000)),
                ('tradeMark', models.SlugField(max_length=500)),
                ('otherRequest', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app6.otherrequest')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app4.usersignup')),
            ],
        ),
        migrations.CreateModel(
            name='medicineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineType', models.CharField(max_length=200)),
                ('medicineQuantity', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.SlugField(max_length=500)),
                ('buildingNumber', models.CharField(max_length=1000)),
                ('tradeMark', models.SlugField(max_length=500)),
                ('medicineRequest', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app6.medicinerequest')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app4.usersignup')),
            ],
        ),
    ]
