# Generated by Django 3.2.8 on 2022-01-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_auto_20220117_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='usereditprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('address', models.SlugField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('aboutme', models.SlugField(max_length=1000)),
            ],
        ),
    ]
