# Generated by Django 3.2.8 on 2022-01-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0005_usereditprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereditprofile',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
