# Generated by Django 3.2.8 on 2022-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0006_usereditprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
