# Generated by Django 3.2.8 on 2022-03-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0006_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
