# Generated by Django 3.2.8 on 2022-02-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0007_userreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='age',
            field=models.IntegerField(),
        ),
    ]
