# Generated by Django 3.2.8 on 2022-04-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_charityfeedback'),
        ('app4', '0008_auto_20220314_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReg',
        ),
        migrations.AlterUniqueTogether(
            name='eventsregistrations',
            unique_together={('user', 'event')},
        ),
    ]
