# Generated by Django 3.2.8 on 2022-04-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0009_auto_20220406_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='isCollected',
            field=models.BooleanField(default=False),
        ),
    ]
