# Generated by Django 3.2.8 on 2022-02-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0009_auto_20220219_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereditprofile',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app4.usersignup'),
        ),
    ]
