# Generated by Django 3.2.8 on 2022-02-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0010_usereditprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='aboutme',
            field=models.SlugField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='address',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='bio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='whatsapp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='usereditprofile',
        ),
    ]
