# Generated by Django 3.2.8 on 2022-02-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0011_auto_20220219_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='confpassword',
        ),
    ]
