# Generated by Django 3.2.8 on 2022-04-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0011_alter_usersignup_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
