# Generated by Django 3.2.8 on 2022-04-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0012_alter_usersignup_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingdonation',
            name='isCollected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicinedonation',
            name='isCollected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherdonation',
            name='isCollected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studymaterialdonation',
            name='isCollected',
            field=models.BooleanField(default=False),
        ),
    ]
