# Generated by Django 3.2.8 on 2022-02-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0012_remove_usersignup_confpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventsRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
                ('userAddress', models.SlugField(verbose_name=250)),
                ('userPhone', models.IntegerField()),
                ('charity', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='app4.usersignup')),
            ],
        ),
    ]
