# Generated by Django 3.2.8 on 2022-02-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0013_eventsregistrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eventsRegistrations',
        ),
    ]
