# Generated by Django 3.2.8 on 2022-02-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0014_delete_eventsregistrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
