# Generated by Django 3.2.8 on 2022-01-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charitysignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charityname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('typeofcharity', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
