# Generated by Django 3.2.8 on 2022-03-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charitysignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charityName', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('address', models.SlugField(max_length=100)),
                ('typeofCharity', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('aboutme', models.SlugField(default='', max_length=1000)),
                ('whatsapp', models.CharField(default='', max_length=50)),
                ('services', models.SlugField(default='', max_length=1000)),
                ('picture', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studymaterialQuantity', models.IntegerField()),
                ('studymaterialExpectedItem', models.CharField(max_length=500)),
                ('studymaterialDiscription', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
        migrations.CreateModel(
            name='OtherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherQuantity', models.IntegerField()),
                ('otherExpectedItem', models.CharField(max_length=500)),
                ('otherDiscription', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineQuantity', models.IntegerField()),
                ('medicineExpectedItem', models.CharField(max_length=500)),
                ('medicineDiscription', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodQuantity', models.IntegerField()),
                ('foodExpectedItem', models.CharField(max_length=500)),
                ('foodDiscription', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothingQuantity', models.IntegerField()),
                ('clothingExpectedItem', models.CharField(max_length=500)),
                ('clothingDiscription', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
        migrations.CreateModel(
            name='addevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=250)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('discription', models.SlugField(max_length=2500)),
                ('image', models.ImageField(upload_to='')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
    ]
