# Generated by Django 3.2.8 on 2022-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitysignup',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charitysignup',
            name='charityname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charitysignup',
            name='confpassword',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charitysignup',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charitysignup',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charitysignup',
            name='phonenumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charitysignup',
            name='typeofcharity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charitysignup',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
