# Generated by Django 3.2.8 on 2022-03-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
    ]
