# Generated by Django 3.2.8 on 2022-04-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_charityfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
                ('foodcollected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.foodrequest')),
            ],
            options={
                'unique_together': {('charity', 'foodcollected')},
            },
        ),
    ]
