# Generated by Django 3.2.8 on 2022-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_auto_20220119_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitysignup',
            name='address',
            field=models.SlugField(max_length=100),
        ),
    ]
