# Generated by Django 3.2.8 on 2022-02-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0003_alter_charitysignup_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='addevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=250)),
                ('starttime', models.TimeField(max_length=250)),
                ('endtime', models.TimeField(max_length=250)),
                ('date', models.DateField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('discription', models.SlugField(max_length=2500)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
