# Generated by Django 3.2.8 on 2022-04-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0003_foodcollected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCollected',
        ),
    ]
