# Generated by Django 3.2.8 on 2022-02-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0004_addevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothingreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.SlugField(max_length=150)),
                ('Quantity', models.IntegerField()),
                ('ExpectedItem', models.CharField(max_length=500)),
                ('Discription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='foodreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.SlugField(max_length=150)),
                ('Quantity', models.IntegerField()),
                ('ExpectedItem', models.CharField(max_length=500)),
                ('Discription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='medicinereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.SlugField(max_length=150)),
                ('Quantity', models.IntegerField()),
                ('ExpectedItem', models.CharField(max_length=500)),
                ('Discription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='otherreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.SlugField(max_length=150)),
                ('Quantity', models.IntegerField()),
                ('ExpectedItem', models.CharField(max_length=500)),
                ('Discription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='studymeterialreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.SlugField(max_length=150)),
                ('Quantity', models.IntegerField()),
                ('ExpectedItem', models.CharField(max_length=500)),
                ('Discription', models.CharField(max_length=1000)),
            ],
        ),
    ]
