# Generated by Django 3.2.8 on 2022-02-15 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0005_clothingreq_foodreq_medicinereq_otherreq_studymeterialreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodQuantity', models.IntegerField()),
                ('foodExpectedItem', models.CharField(max_length=500)),
                ('foodDiscription', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodQuantity', models.IntegerField()),
                ('foodExpectedItem', models.CharField(max_length=500)),
                ('foodDiscription', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodQuantity', models.IntegerField()),
                ('foodExpectedItem', models.CharField(max_length=500)),
                ('foodDiscription', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
        migrations.CreateModel(
            name='OtherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodQuantity', models.IntegerField()),
                ('foodExpectedItem', models.CharField(max_length=500)),
                ('foodDiscription', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodQuantity', models.IntegerField()),
                ('foodExpectedItem', models.CharField(max_length=500)),
                ('foodDiscription', models.CharField(max_length=1000)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
        migrations.DeleteModel(
            name='clothingreq',
        ),
        migrations.DeleteModel(
            name='foodreq',
        ),
        migrations.DeleteModel(
            name='medicinereq',
        ),
        migrations.DeleteModel(
            name='otherreq',
        ),
        migrations.DeleteModel(
            name='studymeterialreq',
        ),
    ]
