# Generated by Django 3.2.8 on 2022-02-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0006_auto_20220215_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingrequest',
            old_name='foodDiscription',
            new_name='clothingDiscription',
        ),
        migrations.RenameField(
            model_name='clothingrequest',
            old_name='foodExpectedItem',
            new_name='clothingExpectedItem',
        ),
        migrations.RenameField(
            model_name='clothingrequest',
            old_name='foodQuantity',
            new_name='clothingQuantity',
        ),
        migrations.RenameField(
            model_name='medicinerequest',
            old_name='foodDiscription',
            new_name='medicineDiscription',
        ),
        migrations.RenameField(
            model_name='medicinerequest',
            old_name='foodExpectedItem',
            new_name='medicineExpectedItem',
        ),
        migrations.RenameField(
            model_name='medicinerequest',
            old_name='foodQuantity',
            new_name='medicineQuantity',
        ),
        migrations.RenameField(
            model_name='otherrequest',
            old_name='foodDiscription',
            new_name='otherDiscription',
        ),
        migrations.RenameField(
            model_name='otherrequest',
            old_name='foodExpectedItem',
            new_name='otherExpectedItem',
        ),
        migrations.RenameField(
            model_name='otherrequest',
            old_name='foodQuantity',
            new_name='otherQuantity',
        ),
        migrations.RenameField(
            model_name='studymaterialrequest',
            old_name='foodDiscription',
            new_name='studymaterialDiscription',
        ),
        migrations.RenameField(
            model_name='studymaterialrequest',
            old_name='foodExpectedItem',
            new_name='studymaterialExpectedItem',
        ),
        migrations.RenameField(
            model_name='studymaterialrequest',
            old_name='foodQuantity',
            new_name='studymaterialQuantity',
        ),
    ]
