# Generated by Django 3.2.8 on 2022-02-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0007_auto_20220215_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charitysignup',
            old_name='charityname',
            new_name='charityName',
        ),
        migrations.RenameField(
            model_name='charitysignup',
            old_name='confpassword',
            new_name='confPassword',
        ),
        migrations.RenameField(
            model_name='charitysignup',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='charitysignup',
            old_name='typeofcharity',
            new_name='typeofCharity',
        ),
        migrations.RenameField(
            model_name='charitysignup',
            old_name='username',
            new_name='userName',
        ),
    ]
