# Generated by Django 3.2.8 on 2022-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0008_auto_20220217_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitysignup',
            name='aboutme',
            field=models.SlugField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='charitysignup',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='charitysignup',
            name='services',
            field=models.SlugField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='charitysignup',
            name='whatsapp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
