# Generated by Django 3.2.8 on 2022-02-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0009_auto_20220223_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charitysignup',
            name='confPassword',
        ),
    ]
