# Generated by Django 3.2.8 on 2022-02-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0010_remove_charitysignup_confpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevents',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addevents',
            name='endtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='addevents',
            name='starttime',
            field=models.TimeField(),
        ),
    ]
