# Generated by Django 3.2.8 on 2022-02-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0016_alter_addevents_charity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addevents',
            name='charity',
        ),
    ]
