# Generated by Django 3.2.8 on 2022-02-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0018_addevents_charity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addevents',
            old_name='charity',
            new_name='charityevents',
        ),
    ]
