# Generated by Django 3.2.8 on 2022-02-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0021_alter_addevents_charityevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addevents',
            name='charityevents',
        ),
    ]
