# Generated by Django 3.2.8 on 2022-02-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0023_addevents_charityevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevents',
            name='charityevents',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup'),
        ),
    ]
