# Generated by Django 3.2.8 on 2022-02-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0025_rename_charityevents_addevents_charity'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventsRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
                ('userAddress', models.SlugField(verbose_name=250)),
                ('userPhone', models.IntegerField()),
            ],
        ),
    ]
