# Generated by Django 3.2.8 on 2022-02-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0027_eventsregistrations_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsregistrations',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup'),
        ),
    ]
