# Generated by Django 3.2.8 on 2022-02-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0030_eventsregistrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsregistrations',
            old_name='charity',
            new_name='user',
        ),
    ]
