# Generated by Django 3.2.8 on 2022-02-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0031_rename_charity_eventsregistrations_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsregistrations',
            name='userAddress',
            field=models.SlugField(max_length=1000),
        ),
    ]
