# Generated by Django 3.2.8 on 2022-02-28 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0032_alter_eventsregistrations_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsregistrations',
            name='userAddress',
        ),
        migrations.RemoveField(
            model_name='eventsregistrations',
            name='userEmail',
        ),
        migrations.RemoveField(
            model_name='eventsregistrations',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='eventsregistrations',
            name='userPhone',
        ),
        migrations.AddField(
            model_name='eventsregistrations',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsregistrations',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app6.addevents'),
        ),
        migrations.AlterField(
            model_name='eventsregistrations',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup'),
        ),
    ]
