# Generated by Django 3.2.8 on 2022-02-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0039_auto_20220228_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eventsRegistrations',
        ),
    ]
