# Generated by Django 3.2.8 on 2022-02-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0040_delete_eventsregistrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app6.addevents')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app6.charitysignup')),
            ],
        ),
    ]
