# Generated by Django 3.2.8 on 2022-02-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0042_alter_eventsregistrations_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsregistrations',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventsregistrations',
            name='user',
        ),
    ]
