# Generated by Django 3.2.8 on 2022-02-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0014_delete_eventsregistrations'),
        ('app6', '0043_auto_20220228_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsregistrations',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app6.addevents'),
        ),
        migrations.AddField(
            model_name='eventsregistrations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app4.usersignup'),
        ),
    ]
